# Generated by Django 4.2.6 on 2023-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_camiseta_delete_paleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('equipo', models.TextField()),
                ('descripcion', models.TextField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('equipo', models.TextField()),
                ('descripcion', models.TextField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.CharField(max_length=30),
        ),
    ]
