# Generated by Django 4.2.6 on 2023-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_datosextra_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='anio',
            field=models.DateField(),
        ),
    ]
