# Generated by Django 4.2.6 on 2023-11-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_camiseta_equipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosExtra',
        ),
    ]
