# Generated by Django 4.2.6 on 2023-11-22 16:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_delete_datosextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=30),
        ),
    ]
