# Generated by Django 4.2.6 on 2023-11-22 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_alter_camiseta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='medias',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
